// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QO8346ubdweBRcewJCUQjZK-ED9jHY4',
    appId: '1:706094513456:web:159b124c87a8b2a2251cf5',
    messagingSenderId: '706094513456',
    projectId: 'synergy-holistic-app',
    authDomain: 'synergy-holistic-app.firebaseapp.com',
    storageBucket: 'synergy-holistic-app.firebasestorage.app',
    measurementId: 'G-5RVHWW6PGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKrfMvG-zB-hHU5O4gWmulrDLT4ldcUq8',
    appId: '1:706094513456:android:71760fd56f1034c4251cf5',
    messagingSenderId: '706094513456',
    projectId: 'synergy-holistic-app',
    storageBucket: 'synergy-holistic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaTgVmx8PTFvs0ZNmZn7_xd40l3h8GkBY',
    appId: '1:706094513456:ios:81a782f99e4008bb251cf5',
    messagingSenderId: '706094513456',
    projectId: 'synergy-holistic-app',
    storageBucket: 'synergy-holistic-app.firebasestorage.app',
    iosBundleId: 'com.example.capproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaTgVmx8PTFvs0ZNmZn7_xd40l3h8GkBY',
    appId: '1:706094513456:ios:81a782f99e4008bb251cf5',
    messagingSenderId: '706094513456',
    projectId: 'synergy-holistic-app',
    storageBucket: 'synergy-holistic-app.firebasestorage.app',
    iosBundleId: 'com.example.capproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QO8346ubdweBRcewJCUQjZK-ED9jHY4',
    appId: '1:706094513456:web:9dcb2c32c63adfca251cf5',
    messagingSenderId: '706094513456',
    projectId: 'synergy-holistic-app',
    authDomain: 'synergy-holistic-app.firebaseapp.com',
    storageBucket: 'synergy-holistic-app.firebasestorage.app',
    measurementId: 'G-ET7FEWWY0E',
  );
}
